language: python

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install tox-travis
  - pip install --no-deps -r requirements/tox.linux.txt

script:
  - tox
  - tox -e codecov
